<?php
/**
 * @file
 * Code for the Linux Homepage feature.
 */

include_once 'linux_landing_pages.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function linux_landing_pages_entity_info_alter(&$entity_info) { 
  $entity_info['node']['view modes']['sidebar'] = array(
    'label' => t('Sidebar'),
    'custom settings' => FALSE,
  );
}
/**
 * Implements hook_node_insert().
 */
function linux_landing_pages_node_insert($node) { 
  if ($node->uuid == '1a77a768-bb9c-412a-b9c5-0e1eb0a326ba') {
    // We are going to set the homepage to the homepage node we imported
    // We first check the node by using the UUID
    // @TODO if this module gets repackaged and the UUID changes then this needs to be updated too!!!!
    $path = 'node/' . $node->nid;
    variable_set('site_frontpage', $path);
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function linux_landing_pages_form_views_exposed_form_alter(&$form, &$form_state) {
  $view = $form_state['view'];
  if ($view->name == 'home_page' && $view->current_display == 'panel_pane_1') {
    $form['#attached']['js'][] = drupal_get_path('module', 'linux_landing_pages') . '/js/landing_page.leftbar.js';
    $form['#attached']['js'][] = drupal_get_path('module', 'linux_landing_pages') . '/js/leftbar.jquery.js';
    $form['#attributes']['class'][] = 'js-leftbar-sort';
  }
}

/**
 * Implements hook_views_ajax_data_alter()
 */
function linux_landing_pages_views_ajax_data_alter(&$commands, $view) {
  // Adds a trigger event to views ajax calls so we can react to them
  if ($view->name == 'home_page' && $view->current_display == 'panel_pane_1') {
    foreach ($commands as $command) {
      if ($command['command'] == 'viewsScrollTop') {
        $selector = $command['selector'];
      }
    }
    $commands[] = array('command' => 'triggerDOMChange');
  }
}