<?php
/**
 * @file
 * Code for the Linux Forum feature.
 */

include_once 'linux_forum.features.inc';

/**
 * Implements hook_uuid_menu_links_info().
 */
function linux_forum_uuid_menu_links_info() {
  return array(
    'forum' => array(
      'original_load_hook' => 'advanced_forum_forum_load',
      'load_hook' => 'linux_forum_forum_load',
      'menu_path' => array('prefix' => 'forum'),
    ),
  );
}

/**
 * Universal forum load function for Drupal's menu.
 *
 * @param mixed $identifier
 *   The identifier of the forum to load, represented as a UUID or TID.
 *
 * @return mixed
 *   Returns the loaded forum object if found, otherwise NULL.
 */
function linux_forum_forum_load($identifier) {
  if (!is_numeric($identifier)) {
    $term = entity_uuid_load('taxonomy_term', array($identifier));
    if (!empty($term)) {
      $term = (object) $term;
      $identifier = $term->tid;
    }
  }
  return advanced_forum_forum_load($identifier);
}

/**
 * Implements hook_module_implements_alter().
 */
function linux_forum_module_implements_alter(&$implementations, $hook) {
  if ('form_taxonomy_form_term_alter' == $hook) {
    $group = $implementations['linux_forum'];
    unset($implementations['linux_forum']);
    $implementations['linux_forum'] = $group;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for taxonomy_form_term().
 *
 * A re-implementation of Path's and UUID Menu Link's taxonomy_form_term()
 * alter implementation as a result of Advanced Forum's
 */
function linux_forum_form_taxonomy_form_term_alter(&$form, $form_state) {
  if (empty($form_state['confirm_delete']) && empty($form['path']['pid']['#value'])) {
    $langcode = entity_language('taxonomy_term', (object) $form['#term']);
    $langcode = !empty($langcode) ? $langcode : LANGUAGE_NONE;
    $conditions = array('source' => 'forum/' . $form['#term']['uuid'], 'language' => $langcode);
    $path = isset($form['#term']['uuid']) ? path_load($conditions) : array();
    if (FALSE === $path) {
      $path = array();
    }
    $path += array(
      'pid' => NULL,
      'source' => isset($form['#term']['uuid']) ? 'forum/' . $form['#term']['uuid'] : NULL,
      'alias' => '',
      'language' => $langcode,
    );
    $form['path']['alias']['#default_value'] = $path['alias'];
    $form['path']['pid']['#value'] = $path['pid'];
    $form['path']['source']['#value'] = $path['source'];
    $form['path']['language']['#value'] = $path['language'];
  }
}
