api = 2
core = 7.x

; Download projects specific for the Linux.com installation profile.
; Contributed modules.
projects[advanced_forum][type] = "module"
projects[advanced_forum][subdir] = "contrib"
projects[advanced_forum][version] = "2.3"
projects[creativecommons][type] = "module"
projects[creativecommons][subdir] = "contrib"
projects[creativecommons][version] = "1.0-alpha2"
projects[creativecommons][patch][] = "https://raw.github.com/imagex/imagex_patches/7.x/contrib/creativecommons/editcontent-strict-error-2103441-1.patch"
projects[flickr][type] = "module"
projects[flickr][subdir] = "contrib"
projects[flickr][version] = "1.1"
projects[pardot][type] = "module"
projects[pardot][subdir] = "contrib"
projects[pardot][version] = "1.0"
projects[radioactivity][type] = "module"
projects[radioactivity][subdir] = "contrib"
projects[radioactivity][version] = "2.8"
projects[og_role_field][type] = "module"
projects[og_role_field][subdir] = "contrib"
projects[og_role_field][version] = "1.0"
projects[og][type] = "module"
projects[og][subdir] = "contrib"
projects[og][version] = "2.3"
projects[migrate][type] = "module"
projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.6-rc1"
projects[migrate_extras][type] = "module"
projects[migrate_extras][subdir] = "contrib"
projects[migrate_extras][version] = "2.5"

; Download ImageX components for this project.
projects[imagex_addthis][type] = "module"
projects[imagex_addthis][subdir] = "imagex/modules"
projects[imagex_addthis][download][type] = "git"
projects[imagex_addthis][download][url] = "git@github.com:amcgowanca/imagex_addthis.git"
projects[imagex_addthis][download][branch] = "core/refactor"

projects[imagex_answers][type] = "module"
projects[imagex_answers][subdir] = "imagex/modules"
projects[imagex_answers][download][type] = "git"
projects[imagex_answers][download][url] = "git@github.com:imagex/imagex_answers.git"
projects[imagex_answers][download][branch] = "7.x-dev"

projects[imagex_blog][type] = "module"
projects[imagex_blog][subdir] = "imagex/modules"
projects[imagex_blog][download][type] = "git"
projects[imagex_blog][download][url] = "git@github.com:imagex/imagex_blog.git"
projects[imagex_blog][download][branch] = "7.x-dev"

projects[imagex_content_featured][type] = "module"
projects[imagex_content_featured][subdir] = "imagex/modules"
projects[imagex_content_featured][download][type] = "git"
projects[imagex_content_featured][download][url] = "git@github.com:imagex/imagex_content_featured.git"
projects[imagex_content_featured][download][branch] = "7.x-dev"

projects[imagex_content_inappropriate][type] = "module"
projects[imagex_content_inappropriate][subdir] = "imagex/modules"
projects[imagex_content_inappropriate][download][type] = "git"
projects[imagex_content_inappropriate][download][url] = "git@github.com:imagex/imagex_content_inappropriate.git"
projects[imagex_content_inappropriate][download][branch] = "7.x-dev"

projects[imagex_content_likes][type] = "module"
projects[imagex_content_likes][subdir] = "imagex/modules"
projects[imagex_content_likes][download][type] = "git"
projects[imagex_content_likes][download][url] = "git@github.com:imagex/imagex_content_likes.git"
projects[imagex_content_likes][download][branch] = "7.x-dev"

projects[imagex_content_pinned][type] = "module"
projects[imagex_content_pinned][subdir] = "imagex/modules"
projects[imagex_content_pinned][download][type] = "git"
projects[imagex_content_pinned][download][url] = "git@github.com:imagex/imagex_content_pinned.git"
projects[imagex_content_pinned][download][branch] = "7.x-dev"

projects[imagex_events][type] = "module"
projects[imagex_events][subdir] = "imagex/modules"
projects[imagex_events][download][type] = "git"
projects[imagex_events][download][url] = "git@github.com:imagex/imagex_events.git"
projects[imagex_events][download][branch] = "7.x-dev"

projects[imagex_faq][type] = "module"
projects[imagex_faq][subdir] = "imagex/modules"
projects[imagex_faq][download][type] = "git"
projects[imagex_faq][download][url] = "git@github.com:imagex/imagex_faq.git"
projects[imagex_faq][download][branch] = "7.x-dev"

projects[imagex_group][type] = "module"
projects[imagex_group][subdir] = "imagex/modules"
projects[imagex_group][download][type] = "git"
projects[imagex_group][download][url] = "git@github.com:imagex/imagex_group.git"
projects[imagex_group][download][branch] = "7.x-dev"

projects[imagex_news][type] = "module"
projects[imagex_news][subdir] = "imagex/modules"
projects[imagex_news][download][type] = "git"
projects[imagex_news][download][url] = "git@github.com:imagex/imagex_news.git"
projects[imagex_news][download][branch] = "7.x-dev"

projects[imagex_poll][type] = "module"
projects[imagex_poll][subdir] = "imagex/modules"
projects[imagex_poll][download][type] = "git"
projects[imagex_poll][download][url] = "git@github.com:amcgowanca/imagex_poll.git"
projects[imagex_poll][download][branch] = "core/refactor"

projects[imagex_wiki][type] = "module"
projects[imagex_wiki][subdir] = "imagex/modules"
projects[imagex_wiki][download][type] = "git"
projects[imagex_wiki][download][url] = "git@github.com:imagex/imagex_wiki.git"
projects[imagex_wiki][download][branch] = "7.x-dev"

projects[imagex_migration][type] = "module"
projects[imagex_migration][subdir] = "imagex/modules"
projects[imagex_migration][download][type] = "git"
projects[imagex_migration][download][url] = "git@github.com:imagex/imagex_migration.git"
projects[imagex_migration][download][branch] = "7.x-dev"

projects[imagex_dbal][type] = "module"
projects[imagex_dbal][subdir] = "imagex/modules"
projects[imagex_dbal][download][type] = "git"
projects[imagex_dbal][download][url] = "git@github.com:imagex/imagex_dbal.git"
projects[imagex_dbal][download][branch] = "7.x-dev"
