<?php
/**
 * @file
 * HybridAuth 48px icon pack.
 */

/**
 * Plugin declaration.
 */
$plugin = array(
  'title' => t('Linux Icons'),
  // The below can be commented out if need be to add styling specific to the icon pack.
  // The Icon styles are already provided by the zocial css setup though.
  // The below should really just be used for positioning and layout.
  //'css' => 'linux_icons.css',
);
