<?php
/**
 * @file
 * Code for the User feature.
 */

include_once 'linux_social_login.features.inc';
/**
 * Implements hook_ctools_plugin_directory().
 */
function linux_social_login_ctools_plugin_directory($module, $type) {
  if ($module == 'hybridauth' && $type == 'icon_pack') {
    return 'plugins/icon_pack';
  }
}

/**
 * Implements hook_preprocess_hybridauth_provider_icon().
 */
function linux_social_login_preprocess_hybridauth_provider_icon(&$vars, $hook) {
  if ($vars['icon_pack'] == 'linux_icons') {
    $icon_pack = hybridauth_get_icon_pack($vars['icon_pack']);
    drupal_add_css($icon_pack['path'] . '/css/zocial.css');
    $vars['icon_pack_classes'] .= ' zocial ' . strtolower($vars['provider_id']);
  }
}