<?php

/**
 * @file
 * Module to provide transition functionality for Linux.com.
 */

/**
 * Implements hook_form_alter().
 */
function linux_transition_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_login' || $form_id == 'user_login_block') {
    if (isset($form_state['input']['name'])) {
      $last_validator = array_pop($form['#validate']);
      $form['#validate'][] = 'linux_transition_login_validate';
      $form['#validate'][] = $last_validator;
    }
  }
}

/**
 * Validation callback to catch the user's password and hash it in Drupal.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form state array.
 */
function linux_transition_login_validate($form, &$form_state) {
  global $user;

  $form_values = $form_state['values'];

  $logged_in = $user->uid || $form_state['uid'];
  $form_errors = form_get_errors() || empty($form_values['name']) || empty($form_values['pass']);

  // Nothing to do if the user is logged in or there are errors.
  if ($logged_in || $form_errors) {
    return;
  }

  // Load the user if the username matches.
  $form_user = db_query('SELECT uid FROM {users} WHERE name = :name',
    array('name' => $form_values['name'])
  )->fetch();
  $account = user_load($form_user->uid);

  // The user doesn't exist.
  if (!$account) {
    return;
  }

  // Check for non-transitioned account.
  $joomla_user = db_query('SELECT * FROM {linux_transition_users} WHERE uid = :uid AND transition_time = 0',
    array(':uid' => $account->uid)
  )->fetch();
  if (!$joomla_user) {
    return;
  }

  if (strpos($joomla_user->password, ':')) {
    list($password, $salt) = explode(':', $joomla_user->password, 2);
  }
  else {
    $password = $joomla_user->password;
    $salt = '';
  }

  // Check the supplied password against the md5.
  if (md5($form_values['pass'] . $salt) == $password || (!$salt && md5($form_values['pass']) == $password)) {
    $user = $account;
    watchdog('linux_transition', 'Converting password for user @name', array('@name' => $user->name));

    // Update the user's Drupal password.
    user_save($user, array('pass' => $form_values['pass']));

    $joomla_user->transition_time = REQUEST_TIME;
    drupal_write_record('linux_transition_users', $joomla_user, array('uid'));

    $form_state['uid'] = $user->uid;
    user_login_finalize($form_values);
  }
}
