<?php
/**
 * @file
 * Code for the Linux Footer feature.
 */

include_once 'linux_footer.features.inc';

function linux_footer_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    case 'entity_presave':
      $altered = array('linux_footer' => $implementations['linux_footer']);
      unset($implementations['linux_footer']);
      $implementations = array_merge($altered, $implementations);
      break;
  }
}


/**
 * Implements hook_entity_presave().
 */
function linux_footer_entity_presave($entity, $type) {
  module_load_include('inc', 'linux_footer', 'linux_footer.features.uuid_bean');
  $beans = linux_footer_uuid_features_default_beans();
  foreach ($beans as $bean) {
    $uuids[] = $bean['uuid'];
  }
  if ($type == 'bean' && in_array($entity->uuid, $uuids)) {
    if (!isset($entity->field_widget_basic__image['und'])) {
      return;
    }
    $files = $entity->field_widget_basic__image['und'];
    unset($entity->field_widget_basic__image['und']);
    foreach ($files as $file) {
      if (empty($file)) {
        continue;
      }

      $footer_logo_path = drupal_get_path('module', 'linux_footer') . '/files/' . $file['filename'];
      if (file_unmanaged_copy($footer_logo_path, $file['uri'], FILE_EXISTS_REPLACE)) {
        $file = (object) $file;
        $file->timestamp = REQUEST_TIME;
        $file->filesize = filesize($file->uri);
        drupal_write_record('file_managed', $file);

        $entity->field_widget_basic__image['und'][] = (array) $file;
      }
      else {
        watchdog('linux', 'Unable to move the @filename into public:// during installation.', array('@filename' => $file['filename']), WATCHDOG_ERROR);
      }
    }
  }
}
