<?php
/**
 * @file
 * Code for the Linux Content Likes feature.
 */

include_once 'linux_content_likes.features.inc';

/**
 * Implements hook_views_api().
 */
function linux_content_likes_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_views_default_views_alter
 */
function linux_content_likes_views_default_views_alter(&$views) {
  if (isset($views['imagex_who_liked_this']->display['page_1'])) {
    unset($views['imagex_who_liked_this']->display['page_1']);
  }
}
