<?php
/**
 * @file
 * linux_question_answer.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function linux_question_answer_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'High Performance',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 12,
    'uuid' => '04eacac9-e6f4-4ba6-9f2a-62ddbdcbe726',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Applications',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '17b672d0-8281-4f65-a191-6981b0714b7e',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Business',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '559e1a5f-b4c7-4140-8dd5-ba85b48504e2',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Drivers',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '62963934-3de4-433c-bbaa-e9c69b94b875',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Clustering',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => '6882fd6e-1603-4b1d-a6b4-05821477ace4',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Storage',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 17,
    'uuid' => '6f6bddec-b2c2-466f-a1ca-27eeaaa4f40b',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Cloud',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '75ef474a-b8f2-4a0a-85bc-81e29a5e7427',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Embedded/Mobile',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '7c6d4c3e-989e-4934-b86b-07783dd6cafe',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Root',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '7deb4b78-65e6-471b-b3d0-dc09947d4b31',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Desktop',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => '8add550c-ffa0-4cd4-bb96-6bc40df2f0c2',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Distributions',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '9d8c6409-e2d1-4889-aa11-8aefa1e51c76',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Networking',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 15,
    'uuid' => 'a48c5772-5428-4eb6-9ef1-a797ff084f9f',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Netbooks',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 14,
    'uuid' => 'b877e86c-0a2f-4e2b-bc08-2269902e6b64',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Phones',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 18,
    'uuid' => 'bb2fb2fc-868a-4df6-8afe-cf92413047ab',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Hardware',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 11,
    'uuid' => 'c1046f94-419b-4b31-8bbe-49842858fefa',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Internet',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 13,
    'uuid' => 'c42225b8-a7ad-409e-acff-7c32c1ef7020',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Audio/Video',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => 'd415ad81-cdcc-4995-a6a4-3ba063e54aba',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Systems Management',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 19,
    'uuid' => 'e3a30b96-0741-4441-b7a7-d5efdb4c3a0c',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Enterprise',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 10,
    'uuid' => 'eb3a0713-0c0f-4bac-bfe8-539c0f53ce41',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'MIDS',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 16,
    'uuid' => 'f8ea7666-8bcf-400e-a00e-7dca3746e067',
    'vocabulary_machine_name' => 'question_category',
    'aggregator_item' => FALSE,
    'metatags' => array(),
  );

  features_alter_code('uuid_term', $terms);

  return $terms;
}
