<?php

/**
 * @file
 * Migrate module for Linux.com.
 */

/**
 * Implements hook_migrate_api().
 */
function linux_migrate_migrate_api() {
  return array(
    'api' => 2,
    'groups' => array(
      'linux' => array(
        'title' => t('Linux.com'),
      )
    ),
    'migrations' => array(
      'User' => array('class_name' => 'UserMigration', 'group_name' => 'linux'),
      //'Content' => array('class_name', 'ContentMigration'),
      'Blog' => array('class_name' => 'BlogMigration', 'group_name' => 'linux'),
      'Question' => array('class_name' => 'QuestionMigration', 'group_name' => 'linux'),
      'Taxonomy Categories' => array('class_name' => 'TaxonomyCategoriesMigration', 'group_name' => 'linux'),
    ),
  );
}
