<?php
/**
 * @file
 * Code for the Linux Dashboard feature.
 */

include_once 'linux_dashboard.features.inc';

/**
 * Implements hook_permission().
 */
function linux_dashboard_permission() {
  return array(
    'view content admin dashboard' => array(
      'title' => t('View Content Admin Dashboard'),
      'description' => t('Allows user view access to the content admin dashboard page.'),
    ),  
  );
}

/**
 * Implements hook_menu_alter().
 */
function linux_dashboard_menu_alter(&$items) {
  // Unset "My Workbench"
  if (!empty($items['admin/workbench'])) {
    $items['admin/workbench']['acess callback'] = FALSE;
  }
  
  // Alter default content admin tab
  if (!empty($items['admin/content'])) {
    $items['admin/content/node']['title'] = 'All Content';
  }
}

/**
 * Implements hook_default_alter().
 *
 * This is a features hook lacking in good docs.
 */
function linux_dashboard_default_page_manager_pages_alter(&$defaults) {
  // Since panels are not added to the dashboard by this module we don't want to store them in this feature
  if (!empty($defaults['linux_dashboard']->default_handlers['page_linux_dashboard_panel_context']->conf['display'])) {
    $display = $defaults['linux_dashboard']->default_handlers['page_linux_dashboard_panel_context']->conf['display'];
    $panes = $display->panels;
  }
}