<?php
/**
 * @file
 * Code for the Linux Dashboard feature.
 */

include_once 'linux_dashboard.features.inc';

/**
 * Implements hook_permission().
 */
function linux_dashboard_permission() {
  return array(
    'view content admin dashboard' => array(
      'title' => t('View Content Admin Dashboard'),
      'description' => t('Allows user view access to the content admin dashboard page.'),
    ),  
  );
}

/**
 * Implements hook_menu_alter().
 */
function linux_dashboard_menu_alter(&$items) {
  // Unset "My Workbench"
  if (!empty($items['admin/workbench'])) {
    $items['admin/workbench']['acess callback'] = FALSE;
  }
  
  // Alter default content admin tab
  if (!empty($items['admin/content'])) {
    $items['admin/content/node']['title'] = 'All Content';
  }
}
